install.packages("devtools", repos = "https://cloud.r-project.org/")
require(devtools)
install_version("shiny", version = "1.5.0", repos = "https://cloud.r-project.org/")
install_version("shinyBS", version = "0.61", repos = "https://cloud.r-project.org/")
install_github("AnalytixWare/ShinySky")
install_version("shinyjs", version = "2.0.0", repos = "https://cloud.r-project.org/")
install_version("shinythemes", version = "1.1.2", repos = "https://cloud.r-project.org/")
install_version("plotly", version = "4.9.2.1", repos = "https://cloud.r-project.org/")
install_version("webshot", version = "0.5.2", repos = "https://cloud.r-project.org/")
webshot::install_phantomjs()
install_version("BiocManager", version = "1.30.10", repos = "https://cloud.r-project.org/")
BiocManager::install("MutationalPatterns")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")
BiocManager::install("BSgenome.Hsapiens.1000genomes.hs37d5")
install_version("ggplot2", version = "3.3.2", repos = "https://cloud.r-project.org/")
install_version("heatmaply", version = "1.1.1", repos = "https://cloud.r-project.org/")
install_version("gplots", version = "3.1.0", repos = "https://cloud.r-project.org/")
install_version("reshape2", version = "1.4.4", repos = "https://cloud.r-project.org/")
install_version("data.table", version="1.13.0", repos = "https://cloud.r-project.org/")
install_version("readxl", version="1.3.1", repos = "https://cloud.r-project.org/")
install_version("openxlsx", version="4.2.2", repos = "https://cloud.r-project.org/")
